Repository ArmaForces/Mods, pull requests merged in 2020-08, with the labels that each got.

#88 Tasks fix default values on conditionEvents*[] entries in example
  addons/tasks/README.md
  addons/tasks/functions/fnc_handleShow.sqf
Labels: bugfix

#86 Allow ACRE Babel and PerSideRadios setup from settings
  addons/acre/$PBOPREFIX$
  addons/acre/CfgEventHandlers.hpp
  addons/acre/README.md
  addons/acre/XEH_PREP.hpp
  addons/acre/XEH_postInit.sqf
  addons/acre/XEH_preInit.sqf
  addons/acre/XEH_preStart.sqf
  addons/acre/config.cpp
  addons/acre/functions/fnc_init.sqf
  addons/acre/functions/script_component.hpp
  addons/acre/initSettings.sqf
  addons/acre/script_component.hpp
  addons/acre/stringtable.xml
  addons/common/XEH_preInit.sqf
  addons/common/stringtable.xml
Labels: feature

#92 Fix spectator not disabled on unconscious
  addons/spectator/XEH_postInit.sqf
Labels: bugfix

#91 Scripted Curator improvements
  addons/curator/XEH_postInit.sqf
  addons/curator/XEH_preInit.sqf
Labels: enhancement

#89 Add ACRE radio gestures
  addons/acre_gestures/$PBOPREFIX$
  addons/acre_gestures/CfgEventHandlers.hpp
  addons/acre_gestures/CfgMoves.hpp
  addons/acre_gestures/XEH_PREP.hpp
  addons/acre_gestures/XEH_postInit.sqf
  addons/acre_gestures/XEH_preInit.sqf
  addons/acre_gestures/XEH_preStart.sqf
  addons/acre_gestures/config.cpp
  addons/acre_gestures/functions/fnc_stopGesture.sqf
  addons/acre_gestures/functions/script_component.hpp
  addons/acre_gestures/initSettings.sqf
  addons/acre_gestures/script_component.hpp
  addons/acre_gestures/stringtable.xml
  addons/common/XEH_preInit.sqf
Labels: enhancement

#94 Save player's group when disconnected
  addons/back_to_game/functions/fnc_dialogConfirm.sqf
  addons/back_to_game/functions/fnc_savePlayerData.sqf
  addons/back_to_game/functions/fnc_teleportPlayer.sqf
Labels: enhancement

#87 Allow setting ACRE channel names from settings
  addons/acre/README.md
  addons/acre/XEH_PREP.hpp
  addons/acre/functions/fnc_getSideChannelNumberVariableName.sqf
  addons/acre/functions/fnc_init.sqf
  addons/acre/functions/fnc_initChannelsNames.sqf
  addons/acre/initSettings.sqf
  addons/acre/initSettingsChannelNames.sqf
  addons/acre/stringtable.xml
Labels: feature
