Repository ArmaForces/Mods, pull requests merged in 2020-03, with the labels that each got.

#55 Play weapon reload animation on AI disembark
  addons/ai_disembark/$PBOPREFIX$
  addons/ai_disembark/CfgEventHandlers.hpp
  addons/ai_disembark/README.md
  addons/ai_disembark/XEH_PREP.hpp
  addons/ai_disembark/XEH_preInit.sqf
  addons/ai_disembark/XEH_preStart.sqf
  addons/ai_disembark/config.cpp
  addons/ai_disembark/functions/fnc_onDisembark.sqf
  addons/ai_disembark/functions/script_component.hpp
  addons/ai_disembark/initSettings.sqf
  addons/ai_disembark/script_component.hpp
  addons/ai_disembark/stringtable.xml
Labels: feature

#56 Run respawn functions in unscheduled
  addons/respawn/CfgRespawnTemplates.hpp
  addons/respawn/functions/fnc_adjustTime.sqf
  addons/respawn/functions/fnc_adjustTimeLocal.sqf
  addons/respawn/functions/fnc_disable.sqf
  addons/respawn/functions/fnc_enable.sqf
  addons/respawn/functions/fnc_onPlayerKilled.sqf
  addons/respawn/functions/fnc_onPlayerRespawn.sqf
Labels: enhancement

#58 Fix curator unassignment
  addons/curator/XEH_postInit.sqf
Labels: bugfix

#57 Add Zeus button to debug console
  addons/curator/XEH_postInit.sqf
  addons/curator/config.cpp
  addons/curator/stringtable.xml
Labels: feature

#54 Tasks framework
  addons/common/XEH_PREP.hpp
  addons/common/functions/fnc_readConfigToNamespace.sqf
  addons/tasks/$PBOPREFIX$
  addons/tasks/CfgEventHandlers.hpp
  addons/tasks/README.md
  addons/tasks/XEH_PREP.hpp
  addons/tasks/XEH_postInit.sqf
  addons/tasks/XEH_preInit.sqf
  addons/tasks/XEH_preStart.sqf
  addons/tasks/config.cpp
  addons/tasks/functions/fnc_cancelUnfinishedTasks.sqf
  addons/tasks/functions/fnc_createTask.sqf
  addons/tasks/functions/fnc_finishTask.sqf
  addons/tasks/functions/fnc_handleFinish.sqf
  addons/tasks/functions/fnc_handleOnFinished.sqf
  addons/tasks/functions/fnc_handleOnShow.sqf
  addons/tasks/functions/fnc_handleShow.sqf
  addons/tasks/functions/fnc_readDestination.sqf
  addons/tasks/functions/fnc_readOwners.sqf
  addons/tasks/functions/fnc_showTask.sqf
  addons/tasks/functions/script_component.hpp
  addons/tasks/script_component.hpp
Labels: feature

#59 Random insurgent units
  .vscode/settings.json
  addons/insurgents/$PBOPREFIX$
  addons/insurgents/CfgEventHandlers.hpp
  addons/insurgents/CfgGroups.hpp
  addons/insurgents/CfgInsurgentGear.hpp
  addons/insurgents/CfgVehicles.hpp
  addons/insurgents/README.md
  addons/insurgents/XEH_PREP.hpp
  addons/insurgents/XEH_preInit.sqf
  addons/insurgents/XEH_preStart.sqf
  addons/insurgents/config.cpp
  addons/insurgents/functions/fnc_addWeaponAmmo.sqf
  addons/insurgents/functions/fnc_randomizeGear.sqf
  addons/insurgents/functions/script_component.hpp
  addons/insurgents/initSettings.sqf
  addons/insurgents/script_component.hpp
  addons/insurgents/stringtable.xml
Labels: feature

#60 Add return type validator for SQF files
  .github/workflows/arma.yml
  addons/killtracker/functions/fnc_dumpStats.sqf
  addons/safestart/functions/fnc_lowerWeapon.sqf
  addons/spectator/functions/fnc_canSpectate.sqf
  tools/return_checker.py
Labels: enhancement, ignore changelog

#61 Bump version for release 1.1.0
  addons/main/script_version.hpp
Labels: ignore changelog
