Repository ArmaForces/Mods, pull requests merged in 2020-10, with the labels that each got.

#105 Add ACE Arsenal category with ACRE radios
  addons/acre/XEH_preInit.sqf
  addons/acre/initSettings.sqf
  addons/acre/stringtable.xml
  addons/common/XEH_preInit.sqf
Labels: enhancement

#103 Code quality improvement in tasks framework
  addons/tasks/functions/fnc_createTask.sqf
Labels: enhancement, ignore changelog

#108 Back to game custom save handlers
  addons/back_to_game/XEH_PREP.hpp
  addons/back_to_game/XEH_preInit.sqf
  addons/back_to_game/functions/fnc_addHandler.sqf
  addons/back_to_game/functions/fnc_dialogConfirm.sqf
  addons/back_to_game/functions/fnc_savePlayerData.sqf
  addons/common/XEH_preInit.sqf
Labels: enhancement

#106 ACRE leader radio copy
  addons/acre/XEH_PREP.hpp
  addons/acre/XEH_preInit.sqf
  addons/acre/config.cpp
  addons/acre/functions/fnc_copyLeaderRadioChildrenActions.sqf
  addons/acre/functions/fnc_copyLeaderSingleRadioChildrenActions.sqf
  addons/acre/functions/fnc_getRadioDisplayName.sqf
  addons/acre/script_component.hpp
  addons/acre/stringtable.xml
  addons/common/XEH_preInit.sqf
Labels: enhancement

#109 Remove dead body when alive player disconnects
  addons/back_to_game/XEH_PREP.hpp
  addons/back_to_game/XEH_postInit.sqf
  addons/back_to_game/functions/fnc_handleDisconnected.sqf
  addons/back_to_game/initSettings.sqf
  addons/back_to_game/stringtable.xml
Labels: enhancement

#111 Prevent saving player data if he was dead when disconnected
  addons/back_to_game/functions/fnc_handleDisconnected.sqf
Labels: bugfix

#110 Fix typo in acre_gestures
  addons/acre_gestures/stringtable.xml
Labels: bugfix, ignore changelog

#116 Remove main menu spotlight added with 2.00
  addons/main_menu/CfgMainMenuSpotlight.hpp
Labels: enhancement

#113 Custom loading main menu loading screen and loading logo overlay
  addons/common/XEH_PREP.hpp
  addons/common/functions/fnc_easterDate.sqf
  addons/loading/$PBOPREFIX$
  addons/loading/CfgEventHandlers.hpp
  addons/loading/CfgLoadingScreen.hpp
  addons/loading/LICENSE
  addons/loading/README.md
  addons/loading/XEH_loadingDisplay.sqf
  addons/loading/config.cpp
  addons/loading/gui.hpp
  addons/loading/script_component.hpp
  addons/loading/stringtable.xml
  addons/loading/ui/loading/cup_0_co.paa
  addons/loading/ui/loading/gm_0_co.paa
  addons/loading/ui/loading/ifa_0_co.paa
  addons/loading/ui/loading/ifa_1_co.paa
  addons/loading/ui/loading/ifa_2_co.paa
  addons/loading/ui/loading/other_0_co.paa
  addons/loading/ui/loading/other_1_co.paa
  addons/loading/ui/loading/postapo_0_co.paa
  addons/loading/ui/loading/rhs_0_co.paa
  addons/loading/ui/loading/rhs_1_co.paa
  addons/loading/ui/loading/rhs_2_co.paa
  addons/loading/ui/loading/rhs_3_co.paa
  addons/loading/ui/loading/rhs_4_co.paa
  addons/loading/ui/loading/rhs_5_co.paa
  addons/loading/ui/loading/rhs_6_co.paa
  addons/loading/ui/loading/unsung_0_co.paa
  addons/loading/ui/loading/unsung_1_co.paa
  addons/loading/ui/loading/vanilla_0_co.paa
  addons/loading/ui/logo_256_ca.paa
  addons/loading/ui/logo_256_dec_ca.paa
  addons/loading/ui/logo_256_easter_ca.paa
  addons/loading/ui/logo_256_oct_ca.paa
  addons/main/script_mod.hpp
Labels: enhancement

#117 Fix main menu loading screen author shown on mission loading screen
  addons/loading/XEH_loadingDisplay.sqf
Labels: bugfix

#119 Filter ACRE radios in back to game data saving
  addons/back_to_game/functions/fnc_savePlayerData.sqf
Labels: bugfix

#120 Fix ace fries duplication
  addons/fries/XEH_postInit.sqf
Labels: bugfix
