Repository ArmaForces/Mods, pull requests merged in 2020-02, with the labels that each got.

#39 Add CODEOWNERS file
  .github/CODEOWNERS
Labels: enhancement, ignore changelog

#40 Add FIRES component
  addons/common/XEH_preInit.sqf
  addons/fries/$PBOPREFIX$
  addons/fries/CfgEventHandlers.hpp
  addons/fries/README.md
  addons/fries/XEH_postInit.sqf
  addons/fries/XEH_preInit.sqf
  addons/fries/config.cpp
  addons/fries/initSettings.sqf
  addons/fries/script_component.hpp
  addons/fries/stringtable.xml
Labels: feature

#41 Add spectator
  addons/common/XEH_PREP.hpp
  addons/common/XEH_preInit.sqf
  addons/common/functions/fnc_isUnconscious.sqf
  addons/spectator/$PBOPREFIX$
  addons/spectator/CfgEventHandlers.hpp
  addons/spectator/XEH_PREP.hpp
  addons/spectator/XEH_postInit.sqf
  addons/spectator/XEH_preInit.sqf
  addons/spectator/XEH_preStart.sqf
  addons/spectator/config.cpp
  addons/spectator/functions/fnc_canSpectate.sqf
  addons/spectator/functions/fnc_disable.sqf
  addons/spectator/functions/fnc_enable.sqf
  addons/spectator/functions/fnc_reloadLocal.sqf
  addons/spectator/functions/fnc_restart.sqf
  addons/spectator/functions/fnc_start.sqf
  addons/spectator/functions/fnc_stop.sqf
  addons/spectator/functions/fnc_toggle.sqf
  addons/spectator/functions/script_component.hpp
  addons/spectator/initSettings.sqf
  addons/spectator/script_component.hpp
  addons/spectator/stringtable.xml
Labels: feature

#42 Add respawn
  addons/respawn/$PBOPREFIX$
  addons/respawn/CfgEventHandlers.hpp
  addons/respawn/CfgRespawnTemplates.hpp
  addons/respawn/XEH_PREP.hpp
  addons/respawn/XEH_postInit.sqf
  addons/respawn/XEH_preInit.sqf
  addons/respawn/XEH_preStart.sqf
  addons/respawn/config.cpp
  addons/respawn/functions/fnc_adjustTime.sqf
  addons/respawn/functions/fnc_adjustTimeLocal.sqf
  addons/respawn/functions/fnc_disable.sqf
  addons/respawn/functions/fnc_enable.sqf
  addons/respawn/functions/fnc_onPlayerKilled.sqf
  addons/respawn/functions/fnc_onPlayerRespawn.sqf
  addons/respawn/functions/fnc_toggle.sqf
  addons/respawn/functions/script_component.hpp
  addons/respawn/initSettings.sqf
  addons/respawn/script_component.hpp
  addons/respawn/stringtable.xml
Labels: feature

#43 Spectator respawn fixes
  addons/respawn/README.md
  addons/spectator/README.md
  addons/spectator/config.cpp
Labels: documentation, enhancement, ignore changelog

#44 Bump version for release 1.0.4
  addons/main/script_version.hpp
Labels: ignore changelog

#45 Add custom high jog coefficient for ACE Advanced Fatigue
  addons/common/XEH_preInit.sqf
  addons/fatigue/$PBOPREFIX$
  addons/fatigue/CfgEventHandlers.hpp
  addons/fatigue/README.md
  addons/fatigue/XEH_PREP.hpp
  addons/fatigue/XEH_postInit.sqf
  addons/fatigue/XEH_preInit.sqf
  addons/fatigue/XEH_preStart.sqf
  addons/fatigue/config.cpp
  addons/fatigue/functions/fnc_toggleHighJogFactor.sqf
  addons/fatigue/functions/script_component.hpp
  addons/fatigue/initSettings.sqf
  addons/fatigue/script_component.hpp
  addons/fatigue/stringtable.xml
Labels: feature

#47 Move game time in spectator to right if respawn counter is enabled
  addons/spectator/CfgEventHandlers.hpp
  addons/spectator/XEH_PREP.hpp
  addons/spectator/functions/fnc_onDisplayLoad.sqf
  addons/spectator/script_component.hpp
Labels: enhancement

#46 Fix Zeus not added properly from Eden attribute
  addons/curator/CfgEden.hpp
  addons/curator/XEH_postInit.sqf
Labels: bugfix

#48 Add launch.json configuration for Arma Debug Engine
  .vscode/launch.json
Labels: ignore changelog

#49 Add function to create player owned marker
  addons/common/XEH_PREP.hpp
  addons/common/XEH_preInit.sqf
  addons/common/functions/fnc_createPlayerMarker.sqf
Labels: feature

#50 Add markers on map when using ACE Tagging on buildings
  addons/common/XEH_preInit.sqf
  addons/tagging/$PBOPREFIX$
  addons/tagging/CfgEventHandlers.hpp
  addons/tagging/README.md
  addons/tagging/XEH_postInit.sqf
  addons/tagging/XEH_preInit.sqf
  addons/tagging/config.cpp
  addons/tagging/initSettings.sqf
  addons/tagging/script_component.hpp
  addons/tagging/stringtable.xml
Labels: feature
