Repository ArmaForces/Mods, pull requests merged in 2020-04, with the labels that each got.

#63 Fix common isUnconcious, Insurgents cleanup
  addons/common/functions/fnc_isUnconscious.sqf
  addons/insurgents/CfgGroups.hpp
  addons/insurgents/CfgVehicles.hpp
  addons/insurgents/stringtable.xml
Labels: bugfix, enhancement

#62 Add AI staying in immobilized vehicle chance
  addons/ai_disembark/XEH_preInit.sqf
  addons/ai_disembark/initSettings.sqf
  addons/ai_disembark/stringtable.xml
Labels: feature

#64 Create flagpoles objects for vanilla country flag markers
  addons/flags/$PBOPREFIX$
  addons/flags/CfgEventHandlers.hpp
  addons/flags/CfgVehicles.hpp
  addons/flags/FlagsVanilla.hpp
  addons/flags/XEH_PREP.hpp
  addons/flags/XEH_postInit.sqf
  addons/flags/XEH_preInit.sqf
  addons/flags/XEH_preStart.sqf
  addons/flags/config.cpp
  addons/flags/functions/script_component.hpp
  addons/flags/script_component.hpp
Labels: feature

#65 Add ability to force grass on all clients
  addons/grass/$PBOPREFIX$
  addons/grass/CfgEventHandlers.hpp
  addons/grass/README.md
  addons/grass/XEH_PREP.hpp
  addons/grass/XEH_postInit.sqf
  addons/grass/XEH_preInit.sqf
  addons/grass/XEH_preStart.sqf
  addons/grass/config.cpp
  addons/grass/functions/fnc_loop.sqf
  addons/grass/functions/fnc_toggle.sqf
  addons/grass/functions/script_component.hpp
  addons/grass/initSettings.sqf
  addons/grass/script_component.hpp
  addons/grass/stringtable.xml
Labels: feature

#66 Fix tasks onShow _taskConfigName undefined error
  addons/tasks/functions/fnc_handleOnShow.sqf
Labels: bugfix

#68 Add support for 2D positions in tasks framework
  addons/tasks/functions/fnc_readDestination.sqf
Labels: enhancement

#67 Fix marker and object not working as task destination
  addons/tasks/XEH_postInit.sqf
  addons/tasks/XEH_preInit.sqf
  addons/tasks/functions/fnc_createTask.sqf
  addons/tasks/functions/fnc_readDestination.sqf
Labels: bugfix

#69 Increase AI Precision to 0.3
  addons/difficulty/CfgAILevelPresets.hpp
Labels: enhancement
