Repository ArmaForces/Mods, pull requests merged in 2021-01, with the labels that each got.

#131 Add broken nightvision goggles
  addons/nightvision/$PBOPREFIX$
  addons/nightvision/CfgEventHandlers.hpp
  addons/nightvision/CfgWeapons.hpp
  addons/nightvision/README.md
  addons/nightvision/XEH_PREP.hpp
  addons/nightvision/XEH_postInit.sqf
  addons/nightvision/XEH_preInit.sqf
  addons/nightvision/XEH_preStart.sqf
  addons/nightvision/config.cpp
  addons/nightvision/functions/script_component.hpp
  addons/nightvision/script_component.hpp
Labels: feature

#132 Add Set_version hemtt script on linux
  hemtt.toml
Labels: bugfix, ignore changelog

#134 Add setting to disable remote sensors on clients
  addons/remotesensors/$PBOPREFIX$
  addons/remotesensors/CfgEventHandlers.hpp
  addons/remotesensors/XEH_preInit.sqf
  addons/remotesensors/config.cpp
  addons/remotesensors/initSettings.sqf
  addons/remotesensors/script_component.hpp
  addons/remotesensors/stringtable.xml
Labels: enhancement

#138 Add information about stringtable usage in tasks framework
  addons/tasks/README.md
Labels: documentation, ignore changelog

#135 Prevent spectator restart if mission not started yet
  addons/spectator/functions/fnc_restart.sqf
Labels: bugfix

#143 Minor Tasks improvements
  addons/tasks/XEH_postInit.sqf
  addons/tasks/XEH_preInit.sqf
  addons/tasks/functions/fnc_createTask.sqf
  addons/tasks/functions/fnc_readOwners.sqf
Labels: enhancement

#141 Add missing requiredAddons in b2g
  addons/back_to_game/config.cpp
Labels: bugfix

#142 Fix main_menu using wrong not unique name in display XEH
  addons/main_menu/CfgEventHandlers.hpp
Labels: bugfix

#145 Move loading screen author to upper right corner
  addons/loading/XEH_loadingDisplay.sqf
  addons/loading/gui.hpp
Labels: enhancement

#146 Radios Arsenal category improvements
  addons/acre/XEH_PREP.hpp
  addons/acre/XEH_preInit.sqf
  addons/acre/functions/fnc_getAllRadios.sqf
Labels: enhancement

#144 Add scripted owners support for tasks
  addons/tasks/README.md
  addons/tasks/functions/fnc_handleOnShow.sqf
Labels: feature

#140 Spectator fixes and improvements
  addons/spectator/XEH_postInit.sqf
  addons/spectator/functions/fnc_onDisplayLoad.sqf
  addons/spectator/script_component.hpp
Labels: bugfix, enhancement

#147 Improve defunct NVGs
  addons/nightvision/CfgWeapons.hpp
  addons/nightvision/data/afm_nvg_defunct.p3d
Labels: enhancement
