Repository ArmaForces/Mods, pull requests merged in 2021-03, with the labels that each got.

#156 Remove AoW spotlights from main menu
  addons/main_menu/CfgMainMenuSpotlight.hpp
Labels: enhancement

#107 Utilize isNotEqualTo
  addons/acre/functions/fnc_initChannelsNames.sqf
  addons/back_to_game/functions/fnc_dialogConfirm.sqf
  addons/insurgents/XEH_preInit.sqf
  addons/insurgents/functions/fnc_randomizeGear.sqf
  addons/spectator/XEH_postInit.sqf
  addons/spectator/functions/fnc_reloadLocal.sqf
  addons/tagging/XEH_postInit.sqf
  addons/tasks/functions/fnc_readDestination.sqf
Labels: enhancement

#158 Use getPlayerID in player markers feature
  addons/common/XEH_preInit.sqf
  addons/common/functions/fnc_createPlayerMarker.sqf
  addons/tagging/XEH_postInit.sqf
Labels: bugfix

#157 Use HashMaps instead of Namespaces
  addons/back_to_game/XEH_preInit.sqf
  addons/back_to_game/functions/fnc_deletePlayerData.sqf
  addons/back_to_game/functions/fnc_getPlayerData.sqf
  addons/back_to_game/functions/fnc_savePlayerData.sqf
  addons/insurgents/XEH_preInit.sqf
  addons/insurgents/script_component.hpp
  addons/tasks/XEH_preInit.sqf
  addons/tasks/functions/fnc_finishTask.sqf
  addons/tasks/functions/fnc_showTask.sqf
Labels: cleanup

#160 Add ACRE setting to change initial direct speech volume
  addons/acre/README.md
  addons/acre/XEH_PREP.hpp
  addons/acre/XEH_postInit.sqf
  addons/acre/functions/fnc_adjustVoiceVolume.sqf
  addons/acre/initSettings.sqf
  addons/acre/script_component.hpp
  addons/acre/stringtable.xml
Labels: feature
