Repository ArmaForces/Mods, pull requests merged in 2023-10, with the labels that each got.

#205 Port faces component from legacy mod
  addons/faces/$PBOPREFIX$
  addons/faces/CfgFaces.hpp
  addons/faces/README.md
  addons/faces/config.cpp
  addons/faces/script_component.hpp
Labels: feature

#202 Spectator - Remove no longer necessary user input enable for ACE unconscious
  addons/spectator/XEH_postInit.sqf
Labels: cleanup

#203 Remove FRIES component
  addons/fries/$PBOPREFIX$
  addons/fries/CfgEventHandlers.hpp
  addons/fries/README.md
  addons/fries/XEH_postInit.sqf
  addons/fries/XEH_preInit.sqf
  addons/fries/config.cpp
  addons/fries/initSettings.sqf
  addons/fries/script_component.hpp
  addons/fries/stringtable.xml
Labels: cleanup

#207 Compatiblity - Fix error popups caused by KKA3 ACE Extension
  .hemtt/project.toml
  addons/compatibility/$PBOPREFIX$
  addons/compatibility/README.md
  addons/compatibility/config.cpp
  addons/compatibility/kka3_ace_extension/CfgMoves.hpp
  addons/compatibility/kka3_ace_extension/config.cpp
  addons/compatibility/kka3_ace_extension/script_component.hpp
  addons/compatibility/script_component.hpp
  addons/main/script_mod.hpp
  include/x/cba/addons/main/script_macros_common.hpp
Labels: enhancement
