Repository ArmaForces/Mods, pull requests merged in 2024-08, with the labels that each got.

#218 Spectator - Allow spectator on player or a group only
  addons/spectator/CfgFunctions.hpp
  addons/spectator/CfgScriptPaths.hpp
  addons/spectator/README.md
  addons/spectator/RscDisplayEGSpectator.hpp
  addons/spectator/XEH_PREP.hpp
  addons/spectator/config.cpp
  addons/spectator/functions/RscDisplayEGSpectator.sqf
  addons/spectator/functions/fnc_EGSpectator.sqf
  addons/spectator/functions/fnc_start.sqf
  addons/spectator/initSettings.inc.sqf
  addons/spectator/stringtable.xml
  include/a3/Functions_F_Exp_A/EGSpectatorCommonDefines.inc
  include/a3/ui_f/hpp/defineDIKCodes.inc
  include/a3/ui_f/hpp/defineResincl.inc
  include/a3/ui_f/hpp/defineResinclDesign.inc
  include/a3/ui_f_exp_a/UI/defineResinclDesign.inc
Labels: feature

#221 Main Menu - Remove Spotlights from SPE 1.1
  addons/main_menu/CfgMainMenuSpotlight.hpp
Labels: enhancement

#220 Tools - Simplify hemtt config with "extends"
  .hemtt/project.toml
Labels: ignore changelog

#222 Spectator - Allow opt-out of unconscious spectator
  addons/spectator/functions/fnc_canSpectate.sqf
  addons/spectator/initSettings.inc.sqf
  addons/spectator/stringtable.xml
Labels: feature

#223 Loading - Add "Śpiulkolot" screen
  addons/loading/CfgLoadingScreen.hpp
  addons/loading/ui/loading/mirko_co.paa
Labels: enhancement
