Repository ArmaForces/Mods, pull requests merged in 2024-09, with the labels that each got.

#225 Common - fix format arg
  addons/common/functions/fnc_modal.sqf
Labels: cleanup

#224 Spectator - Do not use DISPLAY macro
  addons/spectator/functions/RscDisplayEGSpectator.sqf
Labels: bugfix

#226 Tools - Use HEMTT 1.13
  .github/workflows/arma.yml
  .hemtt/launch.toml
  .hemtt/lints.toml
  .hemtt/project.toml
  addons/acre/functions/fnc_initChannelsNames.sqf
  addons/back_to_game/teleportDialog.hpp
  addons/common/script_component.hpp
  addons/curator/CfgEden.hpp
  addons/curator/XEH_preInit.sqf
  addons/debug_console/functions/fnc_initDebugConsole.sqf
  addons/extension_main_menu/XEH_mainDisplay.sqf
  addons/extension_main_menu/functions/fnc_addServerStatusPanel.sqf
  addons/loading/CfgLoadingScreen.hpp
  addons/loading/XEH_loadingDisplay.sqf
  addons/loading/gui.hpp
  addons/main_menu/CfgEventHandlers.hpp
  addons/main_menu/RscDisplayClient.hpp
  addons/main_menu/functions/fnc_join.sqf
  addons/main_menu/script_component.hpp
  addons/spectator/CfgFunctions.hpp
  addons/spectator/config.cpp
  addons/spectator/functions/RscDisplayEGSpectator.sqf
  addons/spectator/functions/fnc_EGSpectator.sqf
  addons/tasks/functions/fnc_readDestination.sqf
  addons/tasks/functions/fnc_readOwners.sqf
  include/a3/functions_f_exp_a/EGSpectatorCommonDefines.inc
  include/a3/ui_f/hpp/defineCommonGrids.inc
  include/a3/ui_f_exp_a/ui/defineResinclDesign.inc
Labels: enhancement
